name: Deploy to Demo Environment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_ref:
        description: 'Git ref to deploy (branch, tag, or SHA)'
        required: true
        default: 'main'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_HOSTNAME: us-central1-docker.pkg.dev
  REPO_NAME: trove-repo
  DOMAIN: ${{ secrets.DOMAIN }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: demo
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.deploy_ref || github.ref }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with gcloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | base64 -d > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCR_HOSTNAME }} --quiet

      - name: Build and push frontend image
        run: |
          docker build -f frontend/prod.Dockerfile -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-frontend:${{ env.IMAGE_TAG }} frontend/
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-frontend:${{ env.IMAGE_TAG }}
          docker tag ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-frontend:${{ env.IMAGE_TAG }} \
                    ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-frontend:latest
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-backend:${{ env.IMAGE_TAG }} backend/
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-backend:${{ env.IMAGE_TAG }}
          docker tag ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-backend:${{ env.IMAGE_TAG }} \
                    ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-backend:latest
          docker push ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-backend:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to instance
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EMAIL: ${{ secrets.DEPLOY_EMAIL }}
        run: |
          scp -i ~/.ssh/deploy_key -r deploy/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/deploy/
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ~/deploy && \
            echo 'DOMAIN=${{ env.DOMAIN }}' > .env && \
            echo 'EMAIL=${{ env.EMAIL }}' >> .env && \
            echo 'DB_PASSWORD=${{ env.DB_PASSWORD }}' >> .env && \
            echo 'GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}' >> .env && \
            echo 'GCR_HOSTNAME=${{ env.GCR_HOSTNAME }}' >> .env && \
            echo 'REPO_NAME=${{ env.REPO_NAME }}' >> .env && \
            echo 'IMAGE_TAG=${{ env.IMAGE_TAG }}' >> .env && \
            make deploy-local
          "

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ~/deploy && make status
          "

      - name: Cleanup old images (if successful)
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            docker system prune -af --filter 'until=168h'
          " 