name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Image tag to rollback to (e.g., commit SHA or "latest")'
        required: true
        default: 'latest'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_HOSTNAME: us-central1-docker.pkg.dev
  REPO_NAME: trove-repo
  DOMAIN: ${{ secrets.DOMAIN }}

jobs:
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    environment: demo
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCR_HOSTNAME }} --quiet

      - name: Verify images exist
        run: |
          gcloud artifacts docker images list ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-frontend --filter="tags:${{ github.event.inputs.rollback_tag }}"
          gcloud artifacts docker images list ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/trove-backend --filter="tags:${{ github.event.inputs.rollback_tag }}"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Execute rollback
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EMAIL: ${{ secrets.DEPLOY_EMAIL }}
          ROLLBACK_TAG: ${{ github.event.inputs.rollback_tag }}
        run: |
          scp -i ~/.ssh/deploy_key -r deploy/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/deploy/
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ~/deploy && \
            echo 'DOMAIN=${{ env.DOMAIN }}' > .env && \
            echo 'EMAIL=${{ env.EMAIL }}' >> .env && \
            echo 'DB_PASSWORD=${{ env.DB_PASSWORD }}' >> .env && \
            echo 'GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}' >> .env && \
            echo 'GCR_HOSTNAME=${{ env.GCR_HOSTNAME }}' >> .env && \
            echo 'REPO_NAME=${{ env.REPO_NAME }}' >> .env && \
            echo 'IMAGE_TAG=${{ env.ROLLBACK_TAG }}' >> .env && \
            ./rollback.sh ${{ env.ROLLBACK_TAG }}
          "

      - name: Verify rollback
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ~/deploy && make status
          " 