name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Image tag to rollback to (e.g. commit SHA or tag)'
        required: true
      services:
        description: 'Services to rollback (comma-separated: frontend,backend)'
        required: true
        default: 'frontend,backend'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCR_HOSTNAME: gcr.io
  DOMAIN: ${{ secrets.DOMAIN }}

jobs:
  rollback:
    name: Rollback Deployment
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout deployment scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            deploy

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Verify images exist
        run: |
          IFS=',' read -ra SERVICES <<< "${{ github.event.inputs.services }}"
          for SERVICE in "${SERVICES[@]}"; do
            gcloud container images describe ${{ env.GCR_HOSTNAME }}/${{ env.GCP_PROJECT_ID }}/trove-${SERVICE}:${{ github.event.inputs.rollback_tag }} \
              || { echo "Image trove-${SERVICE}:${{ github.event.inputs.rollback_tag }} not found"; exit 1; }
          done

      - name: Deploy rollback
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EMAIL: ${{ secrets.DEPLOY_EMAIL }}
          ROLLBACK_TAG: ${{ github.event.inputs.rollback_tag }}
        run: |
          scp -i ~/.ssh/deploy_key -r deploy/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/deploy/
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ~/deploy && \
            echo 'DOMAIN=${{ env.DOMAIN }}' > .env && \
            echo 'EMAIL=${{ env.EMAIL }}' >> .env && \
            echo 'DB_PASSWORD=${{ env.DB_PASSWORD }}' >> .env && \
            echo 'GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}' >> .env && \
            echo 'GCR_HOSTNAME=${{ env.GCR_HOSTNAME }}' >> .env && \
            echo 'IMAGE_TAG=${{ env.ROLLBACK_TAG }}' >> .env && \
            make deploy-local
          "

      - name: Verify Rollback
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ~/deploy && make status
          " 